baseURL: https://www.fairlingtonhistoricalsociety.org
title: Fairlington Historical Society
theme: 
- hugo-book
buildFuture: true

timeout: 300000

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  BookTheme: auto
  BookLogo: favicon.png
  description: Fairlington Historical Society
  images: ["share/share2.jpg"]
#  twitter: "@FairlingtonHistoricalSociety"
#  fb: FairlingtonHistoricalSociety
  title: Fairlington Historical Society
  BookSection: '*'
  booktoc: true

permalinks:
  docs: /:sections[1:]/:contentbasename/
  about: /:sections[1:]/:contentbasename/
  community: /:sections[1:]/:contentbasename/
  highlights: /:sections[1:]/:contentbasename/
  posts: /:year/:month/:slug/

copyright: Fairlington Historical Society
languages:
  en:
    label: "English"
    locale: "en-us"